// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc1Y4k2IcOj-9qs4LQVUCa0qYmZS5NGgQ',
    appId: '1:813688323304:web:2757ad95e4c8bb5f49dd5d',
    messagingSenderId: '813688323304',
    projectId: 'attendancepush-21392',
    authDomain: 'attendancepush-21392.firebaseapp.com',
    databaseURL: 'https://attendancepush-21392.firebaseio.com',
    storageBucket: 'attendancepush-21392.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2r0F3MO2Oq0ZnscTUs7lPmVlmZlh4OHE',
    appId: '1:813688323304:android:71cd8a9e77ca4aa149dd5d',
    messagingSenderId: '813688323304',
    projectId: 'attendancepush-21392',
    databaseURL: 'https://attendancepush-21392.firebaseio.com',
    storageBucket: 'attendancepush-21392.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2vdbvVzCBpQ0Li8DoYjGmqkuoQHY91og',
    appId: '1:813688323304:ios:3e9b2cf04975fec449dd5d',
    messagingSenderId: '813688323304',
    projectId: 'attendancepush-21392',
    databaseURL: 'https://attendancepush-21392.firebaseio.com',
    storageBucket: 'attendancepush-21392.appspot.com',
    iosClientId: '813688323304-h2pulf9b0knblpmlgaif7t8nuelotji4.apps.googleusercontent.com',
    iosBundleId: 'com.cybermeteors.monopoly',
  );
}
